from pydantic import BaseModel, Field
from typing import List, Optional
from typing import List, Optional, Dict, Any
from datetime import datetime

# ---------------------------------------------------------
# Models for individual candidate ranking records
# ---------------------------------------------------------

class CandidateScores(BaseModel):
    """
    Holds the breakdown of all scores generated by the AI for a candidate.
    """
    skill_score: float = Field(0.0, description="Score based on exact skill matches.")
    experience_score: float = Field(0.0, description="Score based on years of experience.")
    education_score: float = Field(0.0, description="Score based on educational background.")
    certification_score: float = Field(0.0, description="Score based on relevant certifications.")
    semantic_score: float = Field(0.0, description="Score based on SBERT semantic similarity.")
    project_score: float = Field(0.0, description="Score based on project relevance.")
    portfolio_score: float = Field(0.0, description="Score based on portfolio analysis.")
    linkedin_score: float = Field(0.0, description="Score based on LinkedIn profile analysis.")
    overall_score: float = Field(0.0, description="The final calculated overall score.")
    xgboost_probability: Optional[float] = Field(None, description="The probability calculated by the XGBoost model.")

class CandidateRankingItem(BaseModel):
    """
    Represents a single candidate's ranking and details in the list.
    """
    ranking_id: int
    candidate_id: int
    job_id: int
    rank_position: int = Field(..., description="The candidate's rank position (1 is best).")
    
    # Candidate details
    candidate_name: str
    candidate_email: Optional[str] = None
    candidate_phone: Optional[str] = None
    
    # Resume details
    resume_id: Optional[int] = None
    resume_status: Optional[str] = None
    linkedin_url: Optional[str] = None
    portfolio_url: Optional[str] = None
    
    # Scores & Recommendation
    scores: CandidateScores
    recommendation: Optional[str] = Field(None, description="AI recommendation text (e.g. 'Highly Recommended').")
    
    # Selection status (Pending / Shortlisted / Waitlisted / Rejected)
    selection_status: str = Field("Pending", description="The recruiter's selection decision for this candidate.")
    
    created_at: datetime


# ---------------------------------------------------------
# Models for API Responses
# ---------------------------------------------------------

class PaginationMetadata(BaseModel):
    """
    Metadata for paginated responses.
    """
    total_items: int
    total_pages: int
    current_page: int
    page_size: int
    has_next: bool
    has_previous: bool

class RankingListResponse(BaseModel):
    """
    The full response returned by the GET /api/rankings/{job_id} endpoint.
    """
    success: bool = True
    message: str = "Rankings retrieved successfully."
    data: List[CandidateRankingItem]
    pagination: PaginationMetadata

class ExtractedEducation(BaseModel):
    degree: Optional[str] = None
    institution: Optional[str] = None
    year: Optional[str] = None
    
class ExtractedExperience(BaseModel):
    title: Optional[str] = None
    company: Optional[str] = None
    duration: Optional[str] = None
    description: Optional[str] = None

class CandidateDetailedResponse(BaseModel):
    """
    The full detailed response for a single candidate.
    """
    success: bool = True
    message: str = "Candidate details retrieved successfully."
    
    # Base info
    candidate_id: int
    job_id: int
    candidate_name: str
    job_title: str
    
    # Status & Rank
    selection_status: str
    rank_position: int
    recommendation: Optional[str] = None
    
    # Contact
    email: Optional[str] = None
    phone: Optional[str] = None
    location: Optional[str] = None
    
    # Resume and Links
    resume_id: Optional[int] = None
    linkedin_url: Optional[str] = None
    portfolio_url: Optional[str] = None
    
    # Extracted Lists
    education: List[ExtractedEducation] = []
    experience: List[ExtractedExperience] = []
    skills: List[str] = []
    
    # Scores
    scores: CandidateScores
    # Full parsed analysis payloads (optional - used by analysis pages)
    linkedin_profile: Optional[Dict[str, Any]] = None
    portfolio_profile: Optional[Dict[str, Any]] = None

class CandidateStatusUpdateRequest(BaseModel):
    status: str = Field(..., description="The new status (e.g. 'Shortlisted', 'Waitlisted', 'Rejected')")

class DecidedCandidateItem(BaseModel):
    id: int
    name: str
    job_id: int
    job: str
    score: float
    recommendation: Optional[str]
    status: str
    decisionDate: str

class DecidedCandidatesResponse(BaseModel):
    success: bool = True
    data: List[DecidedCandidateItem]
